name: build container images

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - reopened
    - synchronize
  push:
    branches:
    - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io/dalinjun/wasm-serverless-poc

jobs:
  build-images:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repo
      uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      with:
        submodules: true

    - name: build crun with WasmEdge support
      run: |
        curl https://raw.githubusercontent.com/WasmEdge/WasmEdge/55dfc3d6f8671ec163addef3137824dae1c301de/utils/install.sh --output install.sh
        chmod u+x install.sh
        ./install.sh --path="/usr/local" --version="0.10.1"

        ./autogen.sh
        ./configure --with-wasmedge
        make
      working-directory: crun

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - if: github.event_name != 'pull_request'
      name: login to container registry
      run: buildah login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

    - name: build Linux image
      run: buildah build -v $HOME/.cargo/registry:/usr/local/cargo/registry -t "$REGISTRY:distroless-latest" -t "$REGISTRY:distroless-$GITHUB_SHA" Dockerfile.distroless
      working-directory: images

    - name: build Webassembly image
      run: buildah build -v $HOME/.cargo/registry:/usr/local/cargo/registry -t "$REGISTRY:wasm-latest" -t "$REGISTRY:wasm-$GITHUB_SHA" --annotation "module.wasm.image/variant=compat-smart" Dockerfile.wasm
      working-directory: images

    - if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      name: push latest images
      run: |
        buildah push "$REGISTRY:distroless-latest"
        buildah push "$REGISTRY:distroless-$GITHUB_SHA"
        buildah push "$REGISTRY:wasm-latest"
        buildah push "$REGISTRY:wasm-$GITHUB_SHA"
