name: build container images

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - reopened
    - synchronize
  push:
    branches:
    - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io/dalinjun/wasm-serverless-poc

jobs:
  build-images:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: login to container registry with oras
      run: |
        oras login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

    - name: build and push crun with WasmEdge support
      run: |
        buildah build --output=type=local,dest=. .
        oras push "$REGISTRY:crun-test" ./crun
      working-directory: crun
