name: build artifacts

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - reopened
    - synchronize
  push:
    branches:
    - main
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io/dalinjun/wasm-serverless-poc

jobs:
  build-images:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - if: github.event_name != 'pull_request'
      name: login to container registry
      run: buildah login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

    - name: build Linux image
      run: buildah build -v $HOME/.cargo/registry:/usr/local/cargo/registry -t "$REGISTRY/distroless:latest" Dockerfile.distroless
      working-directory: images

    - name: build Webassembly image
      run: buildah build -v $HOME/.cargo/registry:/usr/local/cargo/registry -t "$REGISTRY/wasm:latest" --annotation "module.wasm.image/variant=compat-smart" Dockerfile.wasm
      working-directory: images

    - if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
      name: push latest images
      run: |
        buildah push "$REGISTRY/distroless:latest"
        buildah push "$REGISTRY/wasm:latest"

    - if: startsWith(github.ref, 'refs/tags/v')
      name: push release images
      run: |
        buildah tag "$REGISTRY/distroless:latest" "$REGISTRY/distroless:$GITHUB_REF_NAME"
        buildah push "$REGISTRY/distroless:$GITHUB_REF_NAME"

        buildah tag "$REGISTRY/wasm:latest" "$REGISTRY/wasm:$GITHUB_REF_NAME"
        buildah push "$REGISTRY/wasm:$GITHUB_REF_NAME"
